---
deployment:
  tasks:
    - export COMPOSER_ALLOW_SUPERUSER=1
    - /opt/cpanel/composer/bin/composer install --no-interaction --prefer-dist --optimize-autoloader
    - php artisan migrate --force
    - php artisan db:seed --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan optimize
    - php artisan storage:link
